name: CD - Deploy to Production

on:
  push:
    branches:
      - main 
  workflow_dispatch: 

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        run: |
          az aks get-credentials --resource-group ${{ secrets.AZURE_RG }} --name ${{ secrets.AZURE_AKS }}

      - name: Deploy to Production
        run: |
          kubectl create namespace production --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f k8s/ -n production

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/frontend-deployment -n production --timeout=120s
