nname: CI

on:
  push:
    branches: [ testing ]
  pull_request:
    branches: [ testing ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # -------------------------
      # Python backend services
      # -------------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (customer)
        run: pip install -r backend/customer_service/requirements.txt

      - name: Run tests (customer)
        run: |
          cd backend/customer_service
          pytest || echo "No tests found, skipping."

      - name: Install dependencies (order)
        run: pip install -r backend/order_service/requirements.txt

      - name: Run tests (order)
        run: |
          cd backend/order_service
          pytest || echo "No tests found, skipping."

      - name: Install dependencies (product)
        run: pip install -r backend/product_service/requirements.txt

      - name: Run tests (product)
        run: |
          cd backend/product_service
          pytest || echo "No tests found, skipping."

      # -------------------------
      # Frontend
      # -------------------------
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build